name: Show Me the S3cr3tz
on: [push]

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up secret file
      env:
        HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
        FQDN: ${{ secrets.FQDN }}
      run: |
        echo $HEROKU_EMAIL >> secrets.txt
        echo $HEROKU_API_KEY >> secrets.txt
        echo $HEROKU_APP_NAME >> secrets.txt
        echo $FQDN >> secrets.txt

    - name: Run tmate
      uses: mxschmitt/action-tmate@v2
